import "./globals.css";

import Header from "@/components/header";

/*
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body
        className={`antialiased bg-gradient-to-b from-zinc-950 to-zinc-800 pl-5 pr-5 pt-5`} // the coloured background on every page h-screen bg-gradient-to-b from-indigo-800 to-zinc-950 pl-40 pr-40
      >
        <Header></Header> 
        {children} 
      </body>
    </html>
  );
}
